[package]
authors = ["Lexi Frydl <me@lexifry.com>"]
edition = "2018"
name = "delivery"
version = "0.3.0"

[dependencies]
async-std = "1.2"
base64 = "0.11"
digest = "0.8"
meowhash = "0.1"
seahash = "3.0"
