[package]
authors = ["Lexi Frydl <me@lexifry.com>"]
edition = "2018"
name = "delivery"
version = "0.3.0"

[dependencies]
async-std = { version = "1.2", features = ["unstable"] }
base64 = "0.11"
derive_more = "0.99"
digest = "0.8"
meowhash = "0.1"
seahash = "3.0"
